apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: streaming
spec:
  type: ClusterIP
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  namespace: streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      nodeSelector:
        workload-class: data
      containers:
        - name: redpanda
          image: redpandadata/redpanda:v26.1.12
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -lc
          args:
            - |
              exec rpk redpanda start \
                --mode dev-container \
                --check=false \
                --kafka-addr PLAINTEXT://0.0.0.0:9092 \
                --advertise-kafka-addr PLAINTEXT://kafka.streaming.svc.cluster.local:9092
          ports:
            - name: kafka
              containerPort: 9092
          resources:
            requests:
              cpu: "500m"
              memory: 1Gi
            limits:
              memory: 1536Mi
