apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - kafka-compatible-redpanda.yaml
  - kafka-topic-job.yaml
  - pinot-realtime-orders-job.yaml
  - realtime-orders-producer.yaml
